name: Build and Deploy
on:
    push:
        branches:
            -   master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:

          - name: Checkout
            uses: actions/checkout@v2

          - name: Deployment
            uses: appleboy/ssh-action@master

            with:

              host: ${{ secrets.SSH_HOST }}

              key: ${{ secrets.SSH_PRIVATE_KEY }}

              username: ${{ secrets.SSH_USERNAME }}

              script: |

                cd /opt/bitnami/apache2/htdocs/youtube-laravel/public

                git pull origin master

                
